name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with WakaTime Stats
    runs-on: ubuntu-latest
    # This permissions block is the new addition
    permissions:
      contents: write
      
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_OS: "true"
          SHOW_PROJECTS: "false"
          SHOW_EDITORS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_LANGUAGE_PER_REPO: "true"
          SHOW_SHORT_INFO: "true"
          SHOW_LOC_CHART: "false"
          SHOW_LINES_OF_CODE: "true"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_COMMIT: "true"
